### ISSUE TITLE
Download fails for all but one book

### ISSUE THREAD

**Issue by Henry-Jones** [kriegaex/Galileo-Openbook-Cleaner#31]
Hello,

if I specify any book (beside actionscript_1_und_2) the conversion fails with the following stack trace. At this point the zip file is already downloaded.

Is there either a way to fix the software so it will work with the other books as well ?

I've downloaded the zip files manually, is there an option to work on the files directly instead of downloading them ?

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:306)
        at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: de.scrum_master.util.FileDownloader$MD5MismatchException: d:\bu\galileocomputing_vmware.zip: expected c858eff1750f2e3840894a8d1e306a0a, got 53d31675f6ea0bfcbd1dec58f00a144c
        at de.scrum_master.util.FileDownloader.download(FileDownloader.java:154)
        at de.scrum_master.galileo.Downloader.downloadBook(Downloader.java:49)
        at de.scrum_master.galileo.Downloader.download_aroundBody0(Downloader.java:38)
        at de.scrum_master.galileo.Downloader$AjcClosure1.run(Downloader.java:1)
        at de.scrum_master.galileo.LoggingAspect.ajc$around$de_scrum_master_galileo_LoggingAspect$3$798acb89proceed(LoggingAspect.aj:39)
        at de.scrum_master.galileo.LoggingAspect$LoggingAspect$2.log_aroundBody0(LoggingAspect.aj:41)
        at de.scrum_master.galileo.LoggingAspect$LoggingAspect$2.log_aroundBody1$advice(LoggingAspect.aj:15)
        at de.scrum_master.galileo.LoggingAspect$LoggingAspect$2.log(LoggingAspect.aj:1)
        at de.scrum_master.galileo.LoggingAspect.ajc$around$de_scrum_master_galileo_LoggingAspect$3$798acb89(LoggingAspect.aj:41)
        at de.scrum_master.galileo.Downloader.download(Downloader.java:35)
        at de.scrum_master.galileo.OpenbookCleaner.downloadAndCleanBook_aroundBody2(OpenbookCleaner.java:57)
        at de.scrum_master.galileo.OpenbookCleaner$AjcClosure3.run(OpenbookCleaner.java:1)
        at de.scrum_master.galileo.LoggingAspect.ajc$around$de_scrum_master_galileo_LoggingAspect$2$c6d6cf43proceed(LoggingAspect.aj:34)
        at de.scrum_master.galileo.LoggingAspect$LoggingAspect$1.log_aroundBody0(LoggingAspect.aj:36)
        at de.scrum_master.galileo.LoggingAspect$LoggingAspect$1.log_aroundBody1$advice(LoggingAspect.aj:15)
        at de.scrum_master.galileo.LoggingAspect$LoggingAspect$1.log(LoggingAspect.aj:1)
        at de.scrum_master.galileo.LoggingAspect.ajc$around$de_scrum_master_galileo_LoggingAspect$2$c6d6cf43(LoggingAspect.aj:36)
        at de.scrum_master.galileo.OpenbookCleaner.downloadAndCleanBook_aroundBody4(OpenbookCleaner.java:56)
        at de.scrum_master.galileo.OpenbookCleaner.downloadAndCleanBook_aroundBody5$advice(OpenbookCleaner.java:18)
        at de.scrum_master.galileo.OpenbookCleaner.downloadAndCleanBook(OpenbookCleaner.java:1)
        at de.scrum_master.galileo.OpenbookCleaner.main_aroundBody0(OpenbookCleaner.java:31)
        at de.scrum_master.galileo.OpenbookCleaner.main_aroundBody1$advice(OpenbookCleaner.java:12)
        at de.scrum_master.galileo.OpenbookCleaner.main(OpenbookCleaner.java:1)
        ... 6 more
```

**Comment by kriegaex** [comment]
The question has been asked many times, see #28, #29, #30, #24 and others.

**Comment by Henry-Jones** [comment]
Ok, thanks. It works the way you described it in the other tickets.

 

Thanks for the quick reply.

 

Von: Alexander Kriegisch [mailto:notifications@github.com] 
Gesendet: Mittwoch, 11. Mai 2016 22:57
An: kriegaex/Galileo-Openbook-Cleaner <Galileo-Openbook-Cleaner@noreply.github.com>
Cc: Henry-Jones <Henry.Markert@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [kriegaex/Galileo-Openbook-Cleaner] Download fails for all but one book (#31)

 

The question has been asked many times, see #28 <https://github.com/kriegaex/Galileo-Openbook-Cleaner/issues/28> , #29 <https://github.com/kriegaex/Galileo-Openbook-Cleaner/issues/29> , #30 <https://github.com/kriegaex/Galileo-Openbook-Cleaner/issues/30> , #24 <https://github.com/kriegaex/Galileo-Openbo%20ok-Cleaner/issues/24>  and others.
